In [6]:
from __future__ import print_function
import torch

x = torch.empty(5,3) # 5x3의 빈 행렬을 생성한다.
x

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [9]:
x = torch.rand(5, 3) # 5x3의 행렬을 랜덤하게 배정하여 생성한다.
x

tensor([[0.2201, 0.2235, 0.3012],
        [0.4927, 0.7080, 0.0595],
        [0.7008, 0.2477, 0.0458],
        [0.3244, 0.7439, 0.2762],
        [0.0025, 0.9627, 0.9960]])

In [11]:
x = torch.zeros(5,3, dtype=torch.long) # 5 x 3의 0으로 생성한다.
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [13]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

Pytorch 에서는 N-차원의 배열(행렬)을 Tensor라고 부른다. Tensor와 Array의 차이점은 해당 데이터가 GPU 하나의 단위에서 실행될 수 있느냐 없느냐에 따라 다르다.

In [20]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.double) # x의 행렬 shape와 동일한 크기의 랜덤값을 가진 행렬을 생성한다.
print(x)

print("x.size", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1792,  1.1052, -1.4251],
        [-0.2115,  0.3526,  1.8895],
        [-1.2711,  0.0564,  1.1278],
        [ 1.2527, -0.2434, -0.9747],
        [ 1.3429,  0.4614, -1.5843]], dtype=torch.float64)
x.size torch.Size([5, 3])


##### Tensor 연산

In [22]:
y = torch.rand(5,3)

print("x", x)
print("y", y)
print("x+y", x+y)
print("x+y", torch.add(x,y))

x tensor([[-0.1792,  1.1052, -1.4251],
        [-0.2115,  0.3526,  1.8895],
        [-1.2711,  0.0564,  1.1278],
        [ 1.2527, -0.2434, -0.9747],
        [ 1.3429,  0.4614, -1.5843]], dtype=torch.float64)
y tensor([[0.0672, 0.9051, 0.2012],
        [0.3945, 0.3066, 0.9298],
        [0.4652, 0.6668, 0.1014],
        [0.8903, 0.7559, 0.8339],
        [0.4621, 0.7117, 0.2776]])
x+y tensor([[-0.1120,  2.0104, -1.2239],
        [ 0.1830,  0.6592,  2.8194],
        [-0.8059,  0.7232,  1.2292],
        [ 2.1430,  0.5126, -0.1408],
        [ 1.8050,  1.1731, -1.3067]], dtype=torch.float64)
x+y tensor([[-0.1120,  2.0104, -1.2239],
        [ 0.1830,  0.6592,  2.8194],
        [-0.8059,  0.7232,  1.2292],
        [ 2.1430,  0.5126, -0.1408],
        [ 1.8050,  1.1731, -1.3067]], dtype=torch.float64)


In [24]:
result = torch.empty(5,3)

# x+y의 결과값을 out에 지정된 빈 행렬에 저장한다.
torch.add(x, y, out=result)
print(result)

tensor([[-0.1120,  2.0104, -1.2239],
        [ 0.1830,  0.6592,  2.8194],
        [-0.8059,  0.7232,  1.2292],
        [ 2.1430,  0.5126, -0.1408],
        [ 1.8050,  1.1731, -1.3067]])


In [54]:
# x + y의 결과를 곧바로 y에 저장한다.
y.add_(x)

tensor([[ -3.5161,  23.0099, -28.3011],
        [ -3.8354,   7.3580,  38.7208],
        [-24.9574,   1.7940,  22.6572],
        [ 25.9442,  -4.1111, -18.6608],
        [ 27.3194,   9.9389, -31.4081]])

In [63]:
print("x: ", x)
print("x[:, 1]", x[:, 1]) # column에 포함되는 값만 가져오는 slicing 문법
print("x.view(15)", x.view(15)) # resize/reshape 연산

x:  tensor([[-0.1792,  1.1052, -1.4251],
        [-0.2115,  0.3526,  1.8895],
        [-1.2711,  0.0564,  1.1278],
        [ 1.2527, -0.2434, -0.9747],
        [ 1.3429,  0.4614, -1.5843]], dtype=torch.float64)
x[:, 1] tensor([ 1.1052,  0.3526,  0.0564, -0.2434,  0.4614], dtype=torch.float64)
x.view(15) tensor([-0.1792,  1.1052, -1.4251, -0.2115,  0.3526,  1.8895, -1.2711,  0.0564,
         1.1278,  1.2527, -0.2434, -0.9747,  1.3429,  0.4614, -1.5843],
       dtype=torch.float64)


In [66]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

# one element tensor to origin value.
x = torch.randn(1)
print(x)
print(x.item())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([-1.7199])
-1.719934105873108
