In [1]:
import numpy as np
import torch

inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [2]:
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

train_ds = TensorDataset(inputs, targets)

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

# 3 x 2, 총 6개의 weight와 2개의 bias를 가진 Linear 모델을 생성한다.
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)
print(model.parameters())

# weights @ inputs + bias
print(model(inputs))

Parameter containing:
tensor([[ 0.0499,  0.4838, -0.2623],
        [ 0.0381, -0.1787, -0.5609]], requires_grad=True)
Parameter containing:
tensor([0.1424, 0.5728], requires_grad=True)
<generator object Module.parameters at 0x11aa8d450>
tensor([[ 24.9232, -32.7361],
        [ 30.4732, -47.5816],
        [ 54.1026, -52.5896],
        [ 16.3342, -23.9759],
        [ 31.6709, -53.2155]], grad_fn=<AddmmBackward>)


In [3]:
# SGD Optimizer를 생성한다.
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [59]:
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(7703.2725, grad_fn=<MseLossBackward>)


In [60]:
# train
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
    
    print('training loss:', loss_fn(model(inputs), targets))
    
fit(1000, model, loss_fn, opt)

training loss: tensor(0.5772, grad_fn=<MseLossBackward>)


In [61]:
preds = model(inputs)
print("prediction: ", preds)
print("targets: ", targets)

prediction:  tensor([[ 57.1664,  70.2853],
        [ 82.2427, 100.4633],
        [118.6096, 133.4660],
        [ 21.1206,  37.2555],
        [101.9541, 118.5571]], grad_fn=<AddmmBackward>)
targets:  tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
