### Pytorch AUTOGRAD
pytorch는 AUTOGRAD 라고 해서 딥러닝의 핵심인 미분 연산을 자동으로 해주는 매커니즘이 존재한다. Tensor를 생성할 때 인자값으로 `requires_grad=True`를 설정해주면 각 연산이 실행될 때 마다 자동으로 미분 연산 과정을 트래킹 한다. 아래 예제에서는 `Tensor(x)`에 AUTOGRAD를 설정해주었고 `x+2`를 수행하였다. 그 결과 y를 출력해보면 그 미분 연산을 뜻하는 Backward Object `grad_fn`인자에 추가 된 것을 알 수 있다.

In [4]:
import torch

x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 3
out = z.mean()
print(z, out)

tensor([[1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[27., 27.],
        [27., 27.]]) tensor(27.)


`requires_grad` 옵션은 기본적으로 `False`값이다. 중간에 **requires_grad_** 를 이용해서 AUTOGRAD 모드를 활성화 할 수 있다. 다만 그 이전에 수행된 결과들은 미분 과정에 포함되지 않는다.

In [22]:
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [5]:
print("최종 결과인 out의 backward()를 수행한다.")

out.backward()
print(x.grad)

최종 결과인 out의 backward()를 수행한다.


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn